name: Setup Repository

on:
  push:
    branches:
      - main

jobs:
  setup-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create predefined branches
        run: |
          chmod +x create-branches.sh
          ./create-branches.sh

      - name: Set up branch protection rules
        env:
          GITHUB_TOKEN: ${{ secrets.ENV_GITHUB_TOKEN }}
        run: |
          curl -X PUT -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $ENV_GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/branches/main/protection \
            -d '{
              "required_status_checks": {
                "strict": true,
                "contexts": ["Spectral Check"]
              },
              "enforce_admins": true,
              "required_pull_request_reviews": {
                "dismissal_restrictions": {},
                "dismiss_stale_reviews": true,
                "require_code_owner_reviews": true,
                "required_approving_review_count": 1
              },
              "restrictions": null,
              "allow_force_pushes": false,
              "allow_deletions": false
            }'
